# Generated by Django 2.1.2 on 2018-11-07 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_summernote', '0002_update-help_text'),
        ('article', '0002_auto_20181009_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='files',
            field=models.ManyToManyField(blank=True, to='django_summernote.Attachment', verbose_name='прикрепленные файлы'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=170, verbose_name='Название статьи'),
        ),
    ]
